name: Test Authentication Fixes
on:
  pull_request:
    paths:
      - 'oras/provider.py'
      - 'oras/tests/test_auth_functionality.py'
      - '.github/workflows/test-auth-fixes.yml'
  push:
    branches: [ main ]
    paths:
      - 'oras/provider.py'
      - 'oras/tests/test_auth_functionality.py'

jobs:
  test-auth-config-loading:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests
          pip install -e .

      - name: Run authentication fix tests
        run: |
          # Run our functionality test for auth fixes
          python oras/tests/test_auth_functionality.py

      - name: Run syntax validation
        run: |
          # Ensure the provider.py file compiles without syntax errors
          python -m py_compile oras/provider.py

      - name: Check black formatting
        run: |
          pip install black
          black --check oras/provider.py

  test-existing-functionality:
    runs-on: ubuntu-latest
    services:
      registry:
        image: ghcr.io/oras-project/registry:latest
        ports:
          - 5000:5000
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          make install

      - name: Test core registry functionality still works
        env:
          ORAS_HOST: localhost
          ORAS_PORT: 5000
          REGISTRY_STORAGE_DELETE_ENABLED: "true"
        run: |
          # Run a subset of existing tests to ensure we didn't break anything
          pytest oras/tests/test_provider.py::test_annotated_registry_push -v

      - name: Test that auth methods are called
        env:
          ORAS_HOST: localhost
          ORAS_PORT: 5000
        run: |
          # Test our specific auth loading functionality
          python oras/tests/test_auth_functionality.py
